package generator

import (
	"strings"
	"testing"

	"lv-go/internal/models"

	"github.com/stretchr/testify/assert"
)

func TestGenerateTOML(t *testing.T) {
	t.Run("generates basic TOML with single source", func(t *testing.T) {
		config := &models.VectorConfiguration{
			Sources: []models.VectorComponent{
				{
					ComponentID:   "file_source_0",
					ComponentType: models.ComponentTypeSource,
					ComponentKind: "file",
					Config: map[string]interface{}{
						"include":   []string{"/var/log/*.log"},
						"read_from": "end",
					},
					Inputs:   []string{},
					Comments: []string{},
				},
			},
			Transforms: []models.VectorComponent{},
			Sinks:      []models.VectorComponent{},
		}

		toml, err := GenerateTOML(config, "test.conf")
		assert.NoError(t, err)
		assert.Contains(t, toml, "# Generated by lv-go")
		assert.Contains(t, toml, "# Source: test.conf")
		assert.Contains(t, toml, "[sources.file_source_0]")
		assert.Contains(t, toml, `type = "file"`)
		assert.Contains(t, toml, `include = ["/var/log/*.log"]`)
		assert.Contains(t, toml, `read_from = "end"`)
	})

	t.Run("generates TOML with sources, transforms, and sinks", func(t *testing.T) {
		config := &models.VectorConfiguration{
			Sources: []models.VectorComponent{
				{
					ComponentID:   "file_source_0",
					ComponentType: models.ComponentTypeSource,
					ComponentKind: "file",
					Config: map[string]interface{}{
						"include": []string{"/var/log/*.log"},
					},
				},
			},
			Transforms: []models.VectorComponent{
				{
					ComponentID:   "grok_transform_0",
					ComponentType: models.ComponentTypeTransform,
					ComponentKind: "remap",
					Config: map[string]interface{}{
						"source": `. = parse_groks!(.message, ["%{COMMONAPACHELOG}"])`,
					},
					Inputs: []string{"file_source_0"},
				},
			},
			Sinks: []models.VectorComponent{
				{
					ComponentID:   "elasticsearch_sink_0",
					ComponentType: models.ComponentTypeSink,
					ComponentKind: "elasticsearch",
					Config: map[string]interface{}{
						"endpoints": []string{"http://localhost:9200"},
						"mode":      "bulk",
					},
					Inputs: []string{"grok_transform_0"},
				},
			},
		}

		toml, err := GenerateTOML(config, "pipeline.conf")
		assert.NoError(t, err)

		// Check sources section
		assert.Contains(t, toml, "[sources.file_source_0]")
		assert.Contains(t, toml, `type = "file"`)

		// Check transforms section
		assert.Contains(t, toml, "[transforms.grok_transform_0]")
		assert.Contains(t, toml, `type = "remap"`)
		assert.Contains(t, toml, `inputs = ["file_source_0"]`)

		// Check sinks section
		assert.Contains(t, toml, "[sinks.elasticsearch_sink_0]")
		assert.Contains(t, toml, `type = "elasticsearch"`)
		assert.Contains(t, toml, `inputs = ["grok_transform_0"]`)
	})

	t.Run("handles comments properly", func(t *testing.T) {
		config := &models.VectorConfiguration{
			Sources: []models.VectorComponent{
				{
					ComponentID:   "beats_source_0",
					ComponentType: models.ComponentTypeSource,
					ComponentKind: "socket",
					Config: map[string]interface{}{
						"address": "0.0.0.0:5044",
						"mode":    "tcp",
					},
					Comments: []string{
						"NOTE: Beats input migrated to TCP socket",
						"For full Beats protocol support, consider using Filebeat → Vector directly",
					},
				},
			},
		}

		toml, err := GenerateTOML(config, "test.conf")
		assert.NoError(t, err)
		assert.Contains(t, toml, "# NOTE: Beats input migrated to TCP socket")
		assert.Contains(t, toml, "# For full Beats protocol support")
	})

	t.Run("handles multi-line VRL source", func(t *testing.T) {
		config := &models.VectorConfiguration{
			Transforms: []models.VectorComponent{
				{
					ComponentID:   "mutate_transform_0",
					ComponentType: models.ComponentTypeTransform,
					ComponentKind: "remap",
					Config: map[string]interface{}{
						"source": "del(.temp)\ndel(.debug)\n.status = \"processed\"",
					},
					Inputs: []string{"input"},
				},
			},
		}

		toml, err := GenerateTOML(config, "test.conf")
		assert.NoError(t, err)
		// Multi-line strings should use triple quotes
		assert.Contains(t, toml, "'''\n")
		assert.Contains(t, toml, "del(.temp)")
		assert.Contains(t, toml, "del(.debug)")
	})

	t.Run("handles nested config with inline table", func(t *testing.T) {
		config := &models.VectorConfiguration{
			Sinks: []models.VectorComponent{
				{
					ComponentID:   "es_sink_0",
					ComponentType: models.ComponentTypeSink,
					ComponentKind: "elasticsearch",
					Config: map[string]interface{}{
						"endpoints": []string{"http://localhost:9200"},
						"auth": map[string]interface{}{
							"strategy": "basic",
							"user":     "elastic",
							"password": "changeme",
						},
					},
					Inputs: []string{"input"},
				},
			},
		}

		toml, err := GenerateTOML(config, "test.conf")
		assert.NoError(t, err)
		// Should use inline table for small nested structures
		assert.Contains(t, toml, "auth = {")
		assert.Contains(t, toml, `strategy = "basic"`)
		assert.Contains(t, toml, `user = "elastic"`)
		assert.Contains(t, toml, `password = "changeme"`)
	})
}

func TestQuoteValue(t *testing.T) {
	t.Run("quotes simple string", func(t *testing.T) {
		result := quoteValue("test")
		assert.Equal(t, `"test"`, result)
	})

	t.Run("escapes backslashes", func(t *testing.T) {
		result := quoteValue(`C:\path\to\file`)
		assert.Equal(t, `"C:\\path\\to\\file"`, result)
	})

	t.Run("escapes quotes", func(t *testing.T) {
		result := quoteValue(`He said "hello"`)
		assert.Equal(t, `"He said \"hello\""`, result)
	})

	t.Run("escapes both backslashes and quotes", func(t *testing.T) {
		result := quoteValue(`Path: "C:\test"`)
		assert.Equal(t, `"Path: \"C:\\test\""`, result)
	})
}

func TestFormatArray(t *testing.T) {
	t.Run("formats string array", func(t *testing.T) {
		result, err := formatArray([]string{"a", "b", "c"})
		assert.NoError(t, err)
		assert.Equal(t, `["a", "b", "c"]`, result)
	})

	t.Run("handles empty array", func(t *testing.T) {
		result, err := formatArray([]string{})
		assert.NoError(t, err)
		assert.Equal(t, `[]`, result)
	})

	t.Run("escapes special characters in array elements", func(t *testing.T) {
		result, err := formatArray([]string{`path\with\backslash`, `"quoted"`})
		assert.NoError(t, err)
		assert.Contains(t, result, `path\\with\\backslash`)
		assert.Contains(t, result, `\"quoted\"`)
	})
}

func TestFormatValue(t *testing.T) {
	t.Run("formats string", func(t *testing.T) {
		result, err := formatValue("test")
		assert.NoError(t, err)
		assert.Equal(t, `"test"`, result)
	})

	t.Run("formats integer", func(t *testing.T) {
		result, err := formatValue(42)
		assert.NoError(t, err)
		assert.Equal(t, "42", result)
	})

	t.Run("formats boolean", func(t *testing.T) {
		result, err := formatValue(true)
		assert.NoError(t, err)
		assert.Equal(t, "true", result)
	})

	t.Run("formats string array", func(t *testing.T) {
		result, err := formatValue([]string{"a", "b"})
		assert.NoError(t, err)
		assert.Equal(t, `["a", "b"]`, result)
	})

	t.Run("formats multi-line string", func(t *testing.T) {
		result, err := formatValue("line1\nline2\nline3")
		assert.NoError(t, err)
		assert.Contains(t, result, "'''\n")
		assert.Contains(t, result, "line1")
		assert.Contains(t, result, "line2")
	})
}

func TestGenerateComponentID(t *testing.T) {
	t.Run("generates source ID", func(t *testing.T) {
		id := GenerateComponentID("file", models.ComponentTypeSource, 0)
		assert.Equal(t, "file_source_0", id)
	})

	t.Run("generates transform ID", func(t *testing.T) {
		id := GenerateComponentID("grok", models.ComponentTypeTransform, 1)
		assert.Equal(t, "grok_transform_1", id)
	})

	t.Run("generates sink ID", func(t *testing.T) {
		id := GenerateComponentID("elasticsearch", models.ComponentTypeSink, 2)
		assert.Equal(t, "elasticsearch_sink_2", id)
	})
}

func TestShouldUseInlineTable(t *testing.T) {
	t.Run("uses inline for small simple map", func(t *testing.T) {
		m := map[string]interface{}{
			"strategy": "basic",
			"user":     "admin",
		}
		assert.True(t, shouldUseInlineTable(m))
	})

	t.Run("does not use inline for large map", func(t *testing.T) {
		m := map[string]interface{}{
			"a": "1",
			"b": "2",
			"c": "3",
			"d": "4",
		}
		assert.False(t, shouldUseInlineTable(m))
	})

	t.Run("does not use inline for nested map", func(t *testing.T) {
		m := map[string]interface{}{
			"nested": map[string]interface{}{
				"key": "value",
			},
		}
		assert.False(t, shouldUseInlineTable(m))
	})

	t.Run("does not use inline for map with array", func(t *testing.T) {
		m := map[string]interface{}{
			"items": []interface{}{"a", "b"},
		}
		assert.False(t, shouldUseInlineTable(m))
	})
}

func TestFormatMultilineString(t *testing.T) {
	t.Run("formats multi-line string with triple quotes", func(t *testing.T) {
		input := "line1\nline2\nline3"
		result := formatMultilineString(input)
		assert.True(t, strings.HasPrefix(result, "'''\n"))
		assert.True(t, strings.HasSuffix(result, "\n'''"))
		assert.Contains(t, result, "line1")
		assert.Contains(t, result, "line2")
		assert.Contains(t, result, "line3")
	})
}
