input {
    file {
        type => "ap_log"
        path => "app/log/web_*log"
        start_position => "end"

        add_field => { "system" => "ledgendary" }
    }
}

filter {
    grok {
        match => ["path", "%{GREEDYDATA}/%{NOTSPACE:filename}"]
    }

    if [type] == "ap_log" {
        multiline {
            pattern => "%{BASE10NUM}\s\s\s\[%{DATA}\]\sCOrbMsgBus::OrbSrvRecvfun()%{GREEDYDATA}|%{BASE10NUM}   COrbMsgBus::OrbSrvRecvfun()%{GREEDYDATA}"
            negate => true
            what => "previous"
        }
        grok {
            match => { "message" => "duration\sis\s*%{NUMBER:Duration}" }
        }
        mutate {
            convert => { "Duration" => "integer" }
        }
        grok {
            match => { "message" => "srvMethod=\"%{NOTSPACE}\"\s*timeStamp=\"%{NOTSPACE}\s*%{NUMBER:sHr}\:%{NUMBER:sMin}\s*%{NUMBER:sSec}\"" }
        }
    }

}