"""Vector TOML generation using tomlkit."""

from typing import Any

import tomlkit
from tomlkit import comment, document, table

from lv_py.models.vector_config import VectorConfiguration


def _convert_value(value: Any) -> Any:
    """Convert Python values to TOML-compatible types."""
    if isinstance(value, dict):
        t = table()
        for k, v in value.items():
            t[k] = _convert_value(v)
        return t
    elif isinstance(value, list):
        return [_convert_value(item) for item in value]
    else:
        return value


def generate_toml(config: VectorConfiguration) -> str:
    """
    Generate TOML string from VectorConfiguration.

    Args:
        config: Vector configuration to convert

    Returns:
        TOML string with proper formatting and comments
    """
    doc = document()

    # Add header comment
    doc.add(comment("Generated by lv-py - Logstash to Vector Migration Tool"))
    doc.add(comment(f"Source: {config.file_path}"))
    doc.add(tomlkit.nl())

    # Add global options if present
    if config.global_options:
        for key, value in config.global_options.items():
            doc[key] = _convert_value(value)
        doc.add(tomlkit.nl())

    # Add sources (Vector's equivalent of Logstash inputs)
    if config.sources:
        for source_id, source_component in config.sources.items():
            # Add comments if present (for TODO markers)
            if source_component.comments:
                for comm in source_component.comments:
                    doc.add(comment(comm))

            # Create source table
            source_table = table()
            source_table["type"] = source_component.component_kind

            # Add config options
            for key, value in source_component.config.items():
                source_table[key] = _convert_value(value)

            # Add to document
            doc[f"sources.{source_id}"] = source_table
            doc.add(tomlkit.nl())

    # Add transforms (Vector's equivalent of Logstash filters)
    if config.transforms:
        for transform_id, transform_component in config.transforms.items():
            # Add comments if present
            if transform_component.comments:
                for comm in transform_component.comments:
                    doc.add(comment(comm))

            # Create transform table
            transform_table = table()
            transform_table["type"] = transform_component.component_kind

            # Add inputs
            if transform_component.inputs:
                transform_table["inputs"] = transform_component.inputs

            # Add config options
            for key, value in transform_component.config.items():
                transform_table[key] = _convert_value(value)

            # Add to document
            doc[f"transforms.{transform_id}"] = transform_table
            doc.add(tomlkit.nl())

    # Add sinks (Vector's equivalent of Logstash outputs)
    if config.sinks:
        for sink_id, sink_component in config.sinks.items():
            # Add comments if present
            if sink_component.comments:
                for comm in sink_component.comments:
                    doc.add(comment(comm))

            # Create sink table
            sink_table = table()
            sink_table["type"] = sink_component.component_kind

            # Add inputs
            if sink_component.inputs:
                sink_table["inputs"] = sink_component.inputs

            # Add config options
            for key, value in sink_component.config.items():
                sink_table[key] = _convert_value(value)

            # Add to document
            doc[f"sinks.{sink_id}"] = sink_table
            doc.add(tomlkit.nl())

    return tomlkit.dumps(doc)
