"""Vector TOML generation using tomlkit."""

import tomlkit
from tomlkit import comment, document

from lv_py.models.vector_config import VectorConfiguration


def generate_toml(config: VectorConfiguration) -> str:
    """
    Generate TOML string from VectorConfiguration.

    Args:
        config: Vector configuration to convert

    Returns:
        TOML string with proper formatting and comments

    TODO: Implement full TOML generation
    - Convert sources dict to [sources.name] sections
    - Convert transforms dict to [transforms.name] sections
    - Convert sinks dict to [sinks.name] sections
    - Preserve comments for TODO markers (unsupported features)
    - Add global options if present
    """
    doc = document()

    # Placeholder implementation
    doc.add(comment("Generated by lv-py"))
    doc.add(comment("TODO: Add full TOML generation"))

    return tomlkit.dumps(doc)
